max_width = 100
format_code_in_doc_comments = true
fn_single_line = true
format_macro_matchers = true
format_strings = true
merge_derives = false
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
comment_width = 100
report_fixme = "Always"
report_todo = "Unnumbered"
license_template_path = "license_header"
unstable_features = true
