[package]
name = "aluvm"
description = "Functional registry-based RISC virtual machine"
version = "0.10.5"
authors = ["Dr Maxim Orlovsky <orlovsky@ubideco.org>"]
repository = "https://github.com/aluvm/rust-aluvm"
homepage = "https://aluvm.org"
keywords = ["virtual-machine", "emulator", "functional", "risc", "edge-computing"]
categories = ["no-std", "embedded", "compilers", "cryptography", "emulators"]
rust-version = "1.67" # Due to strict encoding library
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
exclude = [".github"]

[lib]
name = "aluvm"

[[bin]]
name = "aluvm-stl"
required-features = ["stl"]

[dependencies]
amplify = { version = "4.5.0", default-features = false, features = ["apfloat", "derive", "hex"] }
paste = "1"
strict_encoding = { version = "2.6.1", default-features = false, features = ["float", "derive"] }
strict_types = { version = "1.6.3", optional = true }
sha2 = "0.10.8"
ripemd = "0.1.3"
baid58 = "0.4.4"
secp256k1 = { version = "0.27.0", optional = true, features = ["global-context"] }
curve25519-dalek = { version = "3.2", optional = true }
half = "~2.2.0" # Required to maintain MSRV
serde_crate = { package = "serde", version = "1", optional = true }

[features]
default = ["std"]
all = ["stl", "std", "secp256k1", "curve25519", "serde"]
stl = ["strict_types/base64", "std"]
std = ["amplify/std"]
alloc = ["amplify/alloc"]
curve25519 = ["curve25519-dalek"]
serde = ["serde_crate", "amplify/serde", "std"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8.4", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.docs.rs]
features = [ "all" ]
